apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: progrium/stress
        command: ["sleep", "3600"]
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
